<template>
  <div id="app">
    <PageHeader :headerLinks="headerLinks" :headerShops="headerShops" :headerCarousel="headerCarousel" /> 
    <Goods :goodsLink="goodsLink"/>
    <GoodsBlue />
    <PopNow :popnowCarousel="popnowCarousel"/>
    <GoodsDelivery :linkShops="linkShops"/>
    <GoodsTryit />
    <HowDeliver :howDeliverListFirst="howDeliverListFirst"  :howDeliverListSecond="howDeliverListSecond"/>
    <Footer :serviseLinks="serviseLinks" :deliveryLinks="deliveryLinks" :footerIcons="footerIcons"/>
  </div>
</template>

<script>
import PageHeader from '@/components/PageHeader'
import Goods from '@/components/Goods'
import GoodsBlue from '@/components/GoodsBlue'
import PopNow from '@/components/PopNow'
import GoodsDelivery from '@/components/GoodsDelivery'
import GoodsTryit from '@/components/GoodsTryit'
import HowDeliver from '@/components/HowDeliver'
import Footer from '@/components/Footer'
export default {
  name: 'app',
  data() {
    return {
      headerLinks: [
        {link: "Санкт-Петербург и ЛО",
        href: "1"},
        {link: "Список магазинов",
        href: "2#"},
        {link: "Как это работает",
        href: "3#"},
        {link: "Доставка для бизнеса",
        href: "4#"},
        {link: "Войти",
        href: "5"},
      ],
      headerShops: [
        {imgSrc: require('@/assets/img/label-shop/label-metro.svg'),
        href: "10"},
        {imgSrc: require('@/assets/img/label-shop/label-lenta.svg'),
        href: "2"},
        {imgSrc: require('@/assets/img/label-shop/label-prisma.svg'),
        href: "3"},
        {imgSrc: require('@/assets/img/label-shop/label-babylon.svg'),
        href: "4"},
        {imgSrc: require('@/assets/img/label-shop/label-vkusvill.svg'),
        href: "1"},
        {imgSrc: require('@/assets/img/label-shop/label-karusel.svg'),
        href: "1"},
        {imgSrc: require('@/assets/img/label-shop/label-auchan.svg'),
        href: "1"}
      ],
      headerCarousel: [
        {class: "profits__wrap--home",
        firstRow: "доставка",
        secondRow: "продуктов",
        thirdRow: "на дом",
        firstTextRow: "Продукты из самых популярных",
        secondTextRow: "гипермаркетов Санкт-Петербурга",
        linkFirst: "1",
        linkFirstText: "Заказать доставку",
        linkSecond: "2",
        linkSecondText: "Выбрать магазин",
        img: require('@/assets/img/bgi-delivery.png'),
        imgClass: "profits__img--delivery",
        classFirstLink: "link--buthrefn"
        },
        {class: "profits__wrap--catalog",
        firstRow: "самый",
        secondRow: "актуальный",
        thirdRow: "каталог",
        firstTextRow: "Ежедневно мы выгружаем актуальный каталог",
        secondTextRow: "товаров для каждого магазина",
        linkFirst: "3",
        linkFirstText: "Смотреть каталог",
        linkSecond: "4",
        linkSecondText: "Выбрать магазин",
        img: require('@/assets/img/bgi-catalog.png'),
        imgClass: "profits__img--catalog",
        classFirstLink: "link--buthrefn"
        },
        {class: "profits__wrap--pack",
        firstRow: "Фасуем товар",
        firstTextRow: "Отдельно овощи, фрукты, хозтовары",
        secondTextRow: "и заморозка. Соблюдаем",
        thirdTextRow: "температурный режим",
        linkFirst: "5",
        linkFirstText: "как это работает",
        linkSecond: "6",
        linkSecondText: "Заказать доставку",
        img: require('@/assets/img/bgi-pack.png'),
        imgClass: "profits__img--catalog",
        classFirstLink: "link--buthrefn"
        },
        {class: "profits__wrap--app",
        firstRow: "Приложение",
        secondRow: "IOS и Android",
        firstTextRow: "Скачайте приложение и заказывайте в любое",
        secondTextRow: "время и в любом мест",
        linkFirst: "7",
        linkSecond: "8",
        firstlinkImg: require('@/assets/img/appstore.svg'),
        secondtlinkImg: require('@/assets/img/google.svg'),
        img: require('@/assets/img/bg-app.png'),
        imgClass: "profits__img--phone",
        classFirstLink: "link--violet"
        },
        {class: "profits__wrap--office",
        firstRow: "Доставляем даже",
        secondRow: "в офисы",
        firstTextRow: "Можем регулярно привозить кофе, чай,",
        secondTextRow: "молоко, овощи и фрукты в офис.",
        linkFirst: "9",
        linkFirstText: "Подробнее для бизнеса",
        linkSecond: "10",
        linkSecondText: "Выбрать магазин",
        img: require('@/assets/img/bgi-office.png'),
        imgClass: "profits__img--catalog",
        classFirstLink: " link--buthrefn link--wide"
        },
      ],
      linkShops: [
        {link: require('@/assets/img/label-shop/label-metro.svg'),
        href: "#"},
        {link: require('@/assets/img/label-shop/label-lenta.svg'),
        href: "#"},
        {link: require('@/assets/img/label-shop/label-prisma.svg'),
        href: "#"},
        {link: require('@/assets/img/label-shop/label-babylon.svg'),
        href: "#"},
        {link: require('@/assets/img/label-shop/label-vkusvill.svg'),
        href: "#"},
        {link: require('@/assets/img/label-shop/label-karusel.svg'),
        href: "#"},
        {link: require('@/assets/img/label-shop/label-auchan.svg'),
        href: "#"}
      ],
      goodsLink: [
				{imgSrc: require('@/assets/img/categories/fruit.png'),
				text: "Овощи и фрукты",
				href: "1"},
				{imgSrc: require('@/assets/img/categories/children.png'),
				text: "Детские товары",
				href: "2"},
        {imgSrc: require('@/assets/img/categories/household.png'),
				text: "Бытовая химия",
				href: "3"},
        {imgSrc: require('@/assets/img/categories/milk.png'),
				text: "Молочные продукты",
				href: "4"},
        {imgSrc: require('@/assets/img/categories/bread.png'),
				text: "Хлеб и выпечка",
				href: "5"},
        {imgSrc: require('@/assets/img/categories/semifinished.png'),
				text: "Полуфабрикаты",
				href: "6"},
        {imgSrc: require('@/assets/img/categories/fish.png'),
				text: "Рыба и морепродукты",
				href: "7"},
        {imgSrc: require('@/assets/img/categories/meat.png'),
				text: "Мясо и птица",
				href: "8"},
        {imgSrc: require('@/assets/img/categories/tea.png'),
				text: "Чай, кофе, какао",
				href: "9"},
        {imgSrc: require('@/assets/img/categories/desert.png'),
				text: "Сладкое",
				href: "10"},
      ],
      serviseLinks: [
        {link: 'Как это работает',
        href: "1"},
        {link: 'Выбор товара и оплата',
        href: "2"},
        {link: 'Доставка',
        href: "3"},
        {link: 'Доставка для бизнеса',
        href: "4"},
        {link: 'Обмен и возврат това',
        href: "5"},
        {link: 'Работа в igooods',
        href: "6"},
        {link: 'Реквизиты франчайзи',
        href: "7"},
        {link: 'Франшиза',
        href: "8"},
      ],
      deliveryLinks: [
        {link: 'METRO доставка продуктов',
        href: "1"},
        {link: 'ЛЕНТА доставка продуктов',
        href: "2"},
        {link: 'ПРИЗМА доставка продуктов',
        href: "3"},
        {link: 'Super Babylon доставка продуктов',
        href: "4"},
        {link: 'ВкусВилл доставка продуктов',
        href: "5"},
        {link: 'КАРУСЕЛЬ доставка продуктов',
        href: "6"},
        {link: 'Ашан доставка продуктов',
        href: "7"},
      ],
      footerIcons: [
        {link: require('@/assets/img/instagram-brands.svg'),
        href: "1"},
        {link: require('@/assets/img/vk-brands.svg'),
        href: "2"},
        {link: require('@/assets/img/telegram-plane-brands.svg'),
        href: "3"},
        {link: require('@/assets/img/facebook-f-brands.svg'),
        href: "4"}
      ],
      popnowCarousel: [
        {imgSrc: require('@/assets/img/label-shop/label-metro.svg'), 
        prodimgSrc: require('@/assets/img/popnow/main_milk.jpg'),
        oldPrice: "96,89 p.",
        priceNow: "89",
        priceGrey: ",89 ₽",
        text: "Молоко ультрапастеризованное 3,5% ТМ Parmalat (Пармалат)",
        volume: "1 л",
        link: "Заказать"
        },
        {imgSrc: require('@/assets/img/label-shop/label-lenta.svg'),
        prodimgSrc: require('@/assets/img/popnow/main_water.png'),
        oldPrice: "36,89 p.",
        priceNow: "29",
        priceGrey: "36,89 ₽",
        text: "Вода природная питьевая негазированная ТМ Святой источник",
        volume: "1,5 л",
        link: "Заказать"
        },
        {imgSrc: require('@/assets/img/label-shop/label-karusel.svg'),
        prodimgSrc: require('@/assets/img/popnow/main_aggs.jpg'),
        oldPrice: "68,88 p.",
        priceNow: "59",
        priceGrey: ",50 ₽",
        text: "Яйцо куриное Экстра С0  ТМ Роскар, 10 штук",
        volume: "630 гр",
        link: "Заказать"
        },
        {imgSrc: require('@/assets/img/label-shop/label-prisma.svg'),
        prodimgSrc: require('@/assets/img/popnow/main_toletPaper.jpg'),
        oldPrice: "91.00 p.",
        priceNow: "37",
        priceGrey: ",00 ₽",
        text: "Туалетная бумага - эконом ТМ Чистый Дом",
        volume: "40 гр",
        link: "Заказать"
        },
        {imgSrc: require('@/assets/img/label-shop/label-auchan.svg'),
        prodimgSrc: require('@/assets/img/popnow/main_cola.jpg'),
        oldPrice: "99.00 p.",
        priceNow: "61",
        priceGrey: ",00 ₽",
        text: "Напиток безалкогольный сильногазированный Coca-Cola zero ТМ Coca-Cola (Кока-Кола)",
        volume: "330 млл",
        link: "Заказать"
        },
        {imgSrc: require('@/assets/img/label-shop/label-vkusvill.svg'),
        prodimgSrc: require('@/assets/img/popnow/main_glass_of_water.jpg'),
        oldPrice: "29.99 p.",
        priceNow: "19",
        priceGrey: ",89 ₽",
        text: "Вода родниковая газированная ТМ ВкусВилл",
        volume: "1 л",
        link: "Заказать"
        },
        {imgSrc: require('@/assets/img/label-shop/label-vkusvill.svg'),
        prodimgSrc: require('@/assets/img/popnow/main_banana.jpeg'),
        oldPrice: "68,88 p.",
        priceNow: "60",
        priceGrey: ",50 ₽",
        text: "Бананы",
        volume: "1 кг",
        link: "Заказать"
        },
        {imgSrc: require('@/assets/img/label-shop/label-metro.svg'),
        prodimgSrc: require('@/assets/img/popnow/main__onion.jpg'),
        oldPrice: "28,88 p.",
        priceNow: "18",
        priceGrey: ",50 ₽",
        text: "Лук репчатый",
        volume: "1 кг",
        link: "Заказать"
        },
        {imgSrc: require('@/assets/img/label-shop/label-lenta.svg'),
        prodimgSrc: require('@/assets/img/popnow/main_tvorog.jpg'),
        oldPrice: "79,00 p.",
        priceNow: "69",
        priceGrey: ",50 ₽",
        text: "Творог 5% ТМ Пискаревский",
        volume: "250 гр",
        link: "Заказать"
        },
      ],
      howDeliverListFirst: [
        {text: "Вы выбираете доступное время доставки. Обычно все делают выбор в пользу доставки в тот же день, и как можно быстрее. Мы стараемся привезти ваш заказ точно к назначенному времени, но отклонение может составить плюс-минус 25 минут. Вы можете отслеживать комплектацию и доставку продуктов питания в Личном кабинете в режиме реального времени."},
        {text: "В торговом зале магазина Ваш заказ собирает Персональный Закупщик igooods. Внимательно и придирчиво. Как для себя! Молочные продукты самые свежие, с максимальной датой (из глубин полки, конечно же!), яйца внутри упаковки целые, овощи-фрукты посимпатичнее и т.д."},
        {text: "Заказ производится через сайт или мобильное приложение интернет-магазина продуктов igooods. Цены в каталоге равны ценам в гипермаркетах Санкт-Петербурга: METRO, ЛЕНТА, PRISMA, ВКУСВИЛЛ, КАРУСЕЛЬ, АШАН и ценам Super Babylon (кроме 4% позиций от общего количества товаров этой сети), включая акционные товары. Оплата заказа - при получении."},
        {text: "Если, пока шёл заказ, какой-то товар или продукт из ассортимента интернет-магазина закончился или у всей партии плохой товарный вид, Персональный Закупщик позвонит Вам, объяснит ситуацию и предложит варианты замен."},
      ],
      howDeliverListSecond: [
        {text: "Перейдите в каталог igooods или скачайте наше приложение:"},
        {text: "Введите название улицы и номер дома; система покажет вам список магазинов продуктов с доставкой от сервиса igooods, доступных по вашему адресу. Выберите продуктовый магазин из этого списка."},
        {text: " Регистрируйтесь, добавляйте товары и продукты в онлайн-корзину, формируйте заказ, в случае любых затруднений звоните по телефону горячей линии в Санкт-Петербурге: 8 (812) 504 89 52 (с 10.00 до 23.00 ежедневно)"},
        {text: " Купите продукты с доставкой на дом по льготной цене 199 рублей для первого заказа!"},
      ],
    }
  },
  components: {
    PageHeader, Goods, GoodsBlue, PopNow, GoodsDelivery, GoodsTryit, HowDeliver, Footer
  }
}
</script>